services:
  web:
    container_name: client
    env_file:
      - ./apps/client/.env
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - crosspost_docker_network
  # api:
  #   container_name: api
  #   build:
  #     context: .
  #     dockerfile: ./apps/api/Dockerfile
  #   restart: always
  #   ports:
  #     - 3001:3001
  #   networks:
  #     - crosspost_docker_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  crosspost_docker_network:
    external: true